version: '3'
services:
  postgres:
    container_name: postgres-links
    hostname: links-app-postgres
    image: postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - link-network

  disposable_link_service:
    image: disposable_link_service
    container_name: disposable_link_service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app'
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - link-network
    working_dir: /code


volumes:
  pgdata:

networks:
  link-network:
    driver: bridge
